language: php
php:
   - "7.0"

env:
  global:
    - THIS_DOCKER_REPO=superflyxxi
    - THIS_DOCKER_LABEL=${TRAVIS_BRANCH}

script: skip

before_install:
  - echo ${THIS_DOCKER_REGISTRY_PASSWORD} | docker login --username ${THIS_DOCKER_REGISTRY_USERNAME} --password-stdin ${THIS_DOCKER_REGISTRY}
  
jobs:
  include:
    - stage: "Build"
      name: "Build docker"
      before_script:
        - if [[ ! ${TRAVIS_BRANCH} =~ (master|v.*) ]]; then
            echo "Caching from ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:master";
            export CACHE_FROM_ARGS="--cache-from ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/httpd-cron:master";
            docker pull ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:master || true;
          fi
      script:
        - find ./src -name "*.php" | xargs -L1 php -l
        - docker build -t ps-store:build --build-arg HTTPD_CRON=${HTTPD_CRON_IMAGE} -f docker/Dockerfile ${CACHE_FROM_ARGS} .
      after_success:
        - docker tag ps-store:build ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:${THIS_DOCKER_LABEL}
        - docker push ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:${THIS_DOCKER_LABEL}
    - stage: "Validation"
      name: "Run tests"
      script:
        - cd tests/
        - find ./ -name "*.php" | xargs -L1 php -l
        - docker pull ${HTTPD_CRON_IMAGE}
        - docker tag ${HTTPD_CRON_IMAGE} httpd-cron:latest
        - docker build -t ps-store:test --build-arg FROM_IMAGE=${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:${THIS_DOCKER_LABEL} .
        - docker run -t --rm --name tests ps-store:test
      after_success:
        - if [[ ! -z "${TRAVIS_TAG}" ]]; then
            docker tag ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:${THIS_DOCKER_LABEL} ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:latest;
            docker push ${THIS_DOCKER_REGISTRY}/${THIS_DOCKER_REPO}/ps-store:latest;
          fi
    - name: "Checkstyle"
      before_install: skip
      language: java
      script:
        - wget --progress=dot:mega "https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.26/checkstyle-8.26-all.jar" -O checkstyle.jar
        - java -jar checkstyle.jar -c checkstyle.xml .

