language: php
php:
   - "7.0"

script:
   - ./build.sh
   - cd tests
   - ./runTests.sh
   - cd ../

after_success:
   - mkdir -p tar/resources
   - mkdir -p tar/bin
   - cp -vR src/* tar/bin/
   - cp -vR resources/* tar/resources/
   - find tar/ -name 'settings_override.ini' -exec rm -v {} \;
   - cd tar/
   - tar -cjvf ../playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2 * 
   - cd ..

deploy:
   provider: releases
   api_key: ${GITHUB_OAUTH_TOKEN}
   skip_cleanup: true
   file: "playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2"
   on:
      tags: true
