language: php
php:
   - "7.0"

script:
   - ./build.sh
   - cd tests
   - ./runTests.sh
   - cd ../
   - mkdir playstation-store-parser-${TRAVIS_BRANCH}
   - cp -vR src/* playstation-store-parser-${TRAVIS_BRANCH}/
   - cp -vR resources/* playstation-store-parser-${TRAVIS_BRANCH}/
   - rm -v playstation-store-parser-${TRAVIS_BRANCH}/src/settings_override.ini || true
   - cd playstation-store-parser-${TRAVIS_BRANCH}
   - tar -cjvf ../playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2 *
   - cd ../

deploy:
   provider: releases
   api_key: ${GITHUB_OAUTH_TOKEN}
   skip_cleanup: true
   file: "playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2"
   on:
      tags: true
