language: php
php:
   - "7.0"

script:
   - ./build.sh
   - cd tests
   - ./runTests.sh
   - cd ../

after_success:
   - mkdir -p playstation-store-parser-${TRAVIS_BRANCH}/resources
   - mkdir -p playstation-store-parser-${TRAVIS_BRANCH}/bin
   - cp -vR src/* playstation-store-parser-${TRAVIS_BRANCH}/bin/
   - cp -vR resources/* playstation-store-parser-${TRAVIS_BRANCH}/resources/
   - find playstation-store-parser-${TRAVIS_BRANCH}/ -name 'settings_override.ini' -exec rm -v {} \;
   - tar -cjvf playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2 playstation-store-parser-${TRAVIS_BRANCH}/*

deploy:
   provider: releases
   api_key: ${GITHUB_OAUTH_TOKEN}
   skip_cleanup: true
   file: "playstation-store-parser-${TRAVIS_BRANCH}.tar.bz2"
   on:
      tags: true
